In [1]:
# input layer
# convolution layer 
# pooling layer
# dense layer
# output layer

In [2]:
import cv2
import numpy as np

In [3]:
# image : data which is  consider in the form of matrix
# it consists of multiple pixels

In [4]:
a = np.zeros([10,10])
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
import wget
demo = wget.download("https://i1.wp.com/autordee.com/wp-content/uploads/2015/11/Koenigsegg-CCR.jpg")

In [22]:
img = cv2.imread(r'Koenigsegg-CCR.jpg',1)

In [23]:
cv2.imshow('car',img)#to display the img
cv2.waitKey(10000)#in milliseconds
cv2.destroyAllWindows()

In [8]:
img.shape

(1532, 2500, 3)

In [9]:
img_resized = cv2.resize(img,(1000,500))
cv2.imshow('car',img_resized)#to display the img
cv2.waitKey(10000)#in milliseconds
cv2.destroyAllWindows()

In [10]:
# image processing 
# converting to gray scale

gray = cv2.cvtColor(img_resized,cv2.COLOR_BGR2GRAY)
cv2.imshow('car',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
# black and white 

bw = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
cv2.imshow('car',bw[0])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# filter / kernel
# for understnding go to setosa.io

In [13]:
import numpy as np
kernel1 = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])
op = cv2.filter2D(img_resized,-1,kernel1)
cv2.imshow('car',op)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
kernel2 = np.ones([3,3])*(1/9)
op2 = cv2.filter2D(img_resized,-1,kernel2)
cv2.imshow('car',op2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
kernel3 = np.array([[-1,-1,-1],[-1,4,-1],[-1,-1,-1]])
op3 = cv2.filter2D(img_resized,-1,kernel3)
cv2.imshow('car',op3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data(path="mnist.npz")

In [17]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [18]:
cv2.imshow('data_set',x_train[0])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# CNN archtitecture

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(32,(3,3),activation='relu'))
model.add(tf.keras.layers.MaxPool2D())
model.add(tf.keras.layers.Flatten()) # max pooling
model.add(tf.keras.layers.Dense(70,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

In [20]:
model.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(),metrics=['accuracy'])

In [21]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100


ValueError: in user code:

    File "c:\Users\yennu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\yennu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\yennu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\yennu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1050, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\yennu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\yennu\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\input_spec.py", line 253, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential' (type Sequential).
    
    Input 0 of layer "conv2d" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (32, 28, 28)
    
    Call arguments received by layer 'sequential' (type Sequential):
      • inputs=tf.Tensor(shape=(32, 28, 28), dtype=uint8)
      • training=True
      • mask=None
